services:
  macos:
    image: dockurr/macos
    container_name: sequoia
    environment:
      VERSION: "15"
      KVM: "N"
      RAM_SIZE: "8G"
      CPU_CORES: "6"
      LANGUAGE: "Chinese"
      REGION: "zh-TW"
      KEYBOARD: "zh-TW"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - ./macos:/storage
    restart: always
    stop_grace_period: 2m