services:
  qemu:
    container_name: cachy
    image: qemux/qemu-arm
    environment:
      BOOT: "cachy"
      KVM: "N"
      RAM_SIZE: "4G"
      CPU_CORES: "6"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      - ./qemu:/storage
    restart: always
    stop_grace_period: 2m