services:
  windows:
    image: dockurr/windows
    container_name: windows10
    environment:
      VERSION: "10"
      KVM: "N"
      RAM_SIZE: "8G"
      CPU_CORES: "6"
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
